import { Container, getContainer } from '@cloudflare/containers'

// `Env` is generated by `wrangler types` from wrangler.jsonc (bindings, vars, secrets).
export class OpenStaff extends Container<Env> {
  defaultPort = 3000
  // The app is stateful; keep the instance warm for a long idle window. Litestream makes a
  // cold start safe when S3_* is configured.
  sleepAfter = '12h'

  constructor(ctx: ConstructorParameters<typeof Container<Env>>[0], env: Env) {
    super(ctx, env)
    // Every string-valued var or secret bound to the Worker becomes a container variable.
    this.envVars = Object.fromEntries(
      Object.entries(env as unknown as Record<string, unknown>).filter((entry): entry is [string, string] => typeof entry[1] === 'string'),
    )
  }
}

export default {
  fetch(request: Request, env: Env): Promise<Response> {
    // A single named instance so every request, cookie, and WebSocket lands on the same SQLite.
    return getContainer(env.OPENSTAFF, 'primary').fetch(request)
  },
} satisfies ExportedHandler<Env>
