import { useEffect, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import type { ComputerProviderInfo, ComputerStatus, StorageStatus } from '@openstaff/shared'
import { api } from '../../lib/api'
import { buttonClass, dangerButtonClass, ErrorText, inputClass, secondaryButtonClass, Section, useAction } from './common'

export function Computer({ owner }: { owner: boolean }) {
  const status = useQuery({ queryKey: ['computer-status'], queryFn: () => api<ComputerStatus>('/api/computer/status'), refetchInterval: 5000 })
  const providers = useQuery({ queryKey: ['computer-providers'], queryFn: () => api<{ providers: ComputerProviderInfo[] }>('/api/computer/providers') })
  const storage = useQuery({ queryKey: ['computer-storage'], queryFn: () => api<StorageStatus>('/api/computer/storage'), refetchInterval: 10_000 })
  const action = useAction(), [selected, setSelected] = useState('local'), [values, setValues] = useState<Record<string, string>>({}), [dismissedNotice, setDismissedNotice] = useState<string>()
  useEffect(() => { if (status.data) setSelected(status.data.provider) }, [status.data?.provider])
  const provider = providers.data?.providers.find((item) => item.id === selected)
  const refresh = async () => { await Promise.all([status.refetch(), providers.refetch(), storage.refetch()]) }
  const disabled = !owner || action.busy || Boolean(status.data?.lockedByEnv)
  return <Section title="Computer">
    {status.data?.detail?.startsWith('Recreated ') && dismissedNotice !== status.data.detail && <div className="mb-4 flex items-start justify-between gap-3 rounded-md border border-waiting/30 bg-waiting/10 p-3 text-sm text-waiting" role="status"><span>{status.data.detail}</span><button type="button" aria-label="Dismiss recreation notice" className="text-waiting hover:text-fg" onClick={() => setDismissedNotice(status.data?.detail)}>×</button></div>}
    <p className="mb-1 text-sm text-fg-muted">Status: <span className="font-medium text-fg">{status.data?.status ?? 'starting'}</span>{status.data?.detail ? ` · ${status.data.detail}` : ''}</p>
    {status.data?.desktop && <p className="mb-3 text-xs text-fg-muted">{status.data.provider === 'e2b' ? `Desktop (Firecracker microVM) · Template: ${status.data.desktop.template ?? 'desktop'} · Stream: ${status.data.desktop.stream ? 'running' : 'stopped'} · CDP: ${status.data.desktop.cdp ? 'ready' : 'unavailable'}` : `Desktop stream: ${status.data.desktop.stream ? 'ready' : 'unavailable'} · CDP: ${status.data.desktop.cdp ? 'ready' : 'unavailable'}`}</p>}
    {status.data?.lockedByEnv && <p className="mb-3 rounded-md border border-waiting/30 bg-waiting/10 p-3 text-sm text-waiting">Locked by COMPUTER_DRIVER. Change the server environment to select another provider.</p>}
    <div className="grid gap-2 sm:grid-cols-2">
      {providers.data?.providers.map((item) => <button key={item.id} type="button" disabled={disabled} onClick={() => { setSelected(item.id); setValues({}) }} className={`rounded-md border p-3 text-left ${selected === item.id ? 'border-line-strong bg-surface-3' : 'border-line bg-surface-2'} disabled:opacity-50`}>
        <div className="flex items-center justify-between"><span className="font-medium">{item.label}</span><span className="text-xs text-fg-muted">{item.configured ? `Configured via ${item.credentialSource ?? 'built-in'}` : 'Not configured'}</span></div>
        <div className="mt-2 flex flex-wrap gap-1">{Object.entries(item.capabilities).filter(([, enabled]) => enabled).map(([name]) => <span key={name} className="rounded-sm bg-surface-4 px-1.5 py-0.5 text-[10px] text-fg-muted">{item.id === 'e2b' && name === 'desktop' ? 'Desktop (Firecracker microVM)' : name}</span>)}</div>
      </button>)}
    </div>
    {provider && <div className="mt-4 rounded-md border border-line bg-surface-2 p-4">
      <div className="flex items-center justify-between"><h3 className="font-medium">{provider.label}</h3><button className={buttonClass} disabled={disabled || selected === status.data?.provider} onClick={() => action.run(async () => { await api('/api/computer/provider', { method: 'PUT', body: JSON.stringify({ id: selected }) }); await refresh() })}>Use this Computer</button></div>
      {provider.managed ? <p className="mt-3 text-sm text-fg-muted">Managed by your host</p> : provider.fields.length > 0 && <div className="mt-3 space-y-2">{provider.fields.map((field) => <label key={field.name} className="block text-sm font-medium">{field.label}<input className={inputClass} type={field.secret ? 'password' : 'text'} placeholder={field.placeholder} required={field.required} value={values[field.name] ?? ''} onChange={(event) => setValues((current) => ({ ...current, [field.name]: event.target.value }))} /></label>)}
        <div className="flex flex-wrap gap-2"><button className={secondaryButtonClass} disabled={!owner || action.busy} onClick={() => action.run(async () => { await api(`/api/computer/providers/${selected}/test`, { method: 'POST', body: JSON.stringify({ values }) }) })}>Test connection</button><button className={buttonClass} disabled={!owner || action.busy} onClick={() => action.run(async () => { await api(`/api/computer/providers/${selected}/credentials`, { method: 'PUT', body: JSON.stringify({ values }) }); setValues({}); await refresh() })}>Save</button>{provider.credentialSource === 'settings' && <button className={dangerButtonClass} disabled={!owner || action.busy} onClick={() => action.run(async () => { await api(`/api/computer/providers/${selected}/credentials`, { method: 'DELETE' }); await refresh() })}>Clear saved key</button>}</div>
      </div>}
    </div>}
    <div data-testid="storage-row" className="mt-4 rounded-md border border-line bg-surface-3 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-medium">Storage</h3><p className="mt-1 text-sm text-fg-muted">{storage.data?.kind === 's3' ? `S3 · ${storage.data.bucket ?? 'bucket unavailable'}` : 'Filesystem'} · {storage.data?.fileCount ?? 0} durable files</p><p className="mt-1 text-xs text-fg-subtle">{storage.data?.lastReconcileAt ? `Last reconciled ${new Date(storage.data.lastReconcileAt).toLocaleString()}` : 'Not reconciled yet'} · {storage.data?.healthy === false ? 'unhealthy' : 'healthy'}</p>{storage.data?.lastWarning && <p className="mt-1 text-xs text-waiting">{storage.data.lastWarning}</p>}</div><button className={buttonClass} disabled={!owner || action.busy} onClick={() => action.run(async () => { await api('/api/computer/storage/sync', { method: 'POST', body: '{}' }); await refresh() })}>Sync now</button></div></div>
    <div className="mt-4 flex flex-wrap gap-2"><button className={secondaryButtonClass} disabled={!owner || action.busy} onClick={() => action.run(async () => { await api('/api/computer/restart', { method: 'POST' }); await refresh() })}>Restart</button>{provider?.capabilities.explicitStop && <button className={secondaryButtonClass} disabled={!owner || action.busy} onClick={() => action.run(async () => { await api('/api/computer/stop', { method: 'POST' }); await refresh() })}>Stop</button>}<button className={dangerButtonClass} disabled={!owner || action.busy} onClick={() => { if (window.confirm('Destroy this Computer? Its attached volume and non-durable remote files will be permanently removed. Durable storage objects are kept.')) action.run(async () => { await api('/api/computer/destroy', { method: 'POST', body: JSON.stringify({ confirm: true }) }); await refresh() }) }}>Destroy</button></div>
    <ErrorText error={action.error || status.data?.error || status.error?.message || providers.error?.message || storage.error?.message} />
  </Section>
}
