import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link } from '@tanstack/react-router'
import type { PluginServerAuth } from '@openstaff/shared'
import { openConnectionPopup } from '../../lib/connection-popup'
import { useConnectionUpdates } from '../../hooks/useConnectedApps'
import { api } from '../../lib/api'
import { ConnectDialog } from '../ConnectDialog'
import { dangerButtonClass, ErrorText, secondaryButtonClass, Section, useAction } from './common'

interface ConnectionList { connections: Array<{ id: string; toolkit: string; status: string }>; servers: Array<PluginServerAuth & { pluginId: string; appName: string }>; clients: Array<{ issuer: string; clientId: string }> }
export function Connections() {
  useConnectionUpdates()
  const query = useQuery({ queryKey: ['connections'], queryFn: () => api<ConnectionList>('/api/connections'), refetchInterval: 2000 })
  const [selected, setSelected] = useState<{ pluginId: string; name: string }>(), action = useAction()
  const remove = (path: string, body?: unknown) => action.run(async () => { await api(path, { method: 'DELETE', ...(body ? { body: JSON.stringify(body) } : {}) }); await query.refetch() })
  return <Section title="Connections"><div className="mb-4 divide-y divide-line">{query.data?.connections.map((item) => <div key={item.id} className="py-3 text-sm"><div className="flex justify-between"><span className="capitalize">{item.toolkit} <span className="text-xs text-fg-subtle">Composio</span></span><span className={item.status === 'ACTIVE' ? 'text-ok' : 'text-waiting'}>{item.status === 'ACTIVE' ? 'Connected' : item.status === 'EXPIRED' ? 'Expired' : item.status === 'INITIATED' ? 'Connecting' : 'Error'}</span></div><div className="mt-2 flex flex-wrap gap-2"><button onClick={() => void action.run(async () => { openConnectionPopup(`/api/connections/start?toolkit=${encodeURIComponent(item.toolkit)}`) })} className={secondaryButtonClass}>Reconnect</button><button disabled={action.busy} className={dangerButtonClass} onClick={() => remove(`/api/connections/${item.id}`)}>Disconnect</button></div></div>)}{query.data?.servers.filter((item) => item.auth !== 'none').map((item) => <div key={`${item.pluginId}/${item.name}`} aria-label={`Server ${item.name}`} className="py-3 text-sm"><div className="flex justify-between"><span>{item.appName} <span className="text-xs text-fg-subtle">Plugin</span></span><span className={item.connected ? 'text-ok' : 'text-waiting'}>{item.status}</span></div><p className="mt-1 text-xs text-fg-subtle">Last checked: {item.lastCheckedAt ? new Date(item.lastCheckedAt).toLocaleString() : 'Not checked yet'}</p>{item.refreshError && <p className="mt-1 text-xs text-waiting">{item.refreshError}</p>}<div className="mt-2 flex flex-wrap gap-2"><button className={secondaryButtonClass} onClick={() => setSelected(item)}>{item.connected ? 'Reconnect' : 'Connect'}</button><button disabled={action.busy} className={dangerButtonClass} onClick={() => remove(`/api/plugins/${item.pluginId}/servers/${encodeURIComponent(item.name)}/connection`)}>Disconnect</button></div></div>)}{query.data?.clients.map((item) => <div key={item.issuer} className="py-3 text-sm"><div className="flex justify-between gap-3"><span className="break-all">{item.issuer}<span className="mt-1 block text-xs text-fg-subtle">Shared OAuth client · Configured</span></span><button disabled={action.busy} className={`${dangerButtonClass} shrink-0`} onClick={() => remove('/api/connections/clients', { issuer: item.issuer })}>Forget client</button></div></div>)}</div><Link to="/marketplace" className="text-sm text-fg underline underline-offset-4">Connect an app</Link>{selected && <ConnectDialog pluginId={selected.pluginId} serverName={selected.name} onClose={() => { setSelected(undefined); void query.refetch() }} />}<ErrorText error={action.error || query.error?.message} /></Section>
}
